# Generated by Django 6.1 on 2026-09-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('tech_stack', models.CharField(blank=True, help_text='Pisahkan setiap teknologi dengan koma, contoh: Django, PostgreSQL, React', max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('project_url', models.URLField(blank=True, help_text='Link demo/live project (opsional)')),
                ('source_url', models.URLField(blank=True, help_text='Link repository/source code (opsional)')),
                ('started_at', models.DateField()),
                ('is_ongoing', models.BooleanField(default=False)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-started_at'],
            },
        ),
    ]
